import {Footer} from "@/app/ui/footer";
import '@/app/ui/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    <Footer/>
    </html>
  )
}
